apiVersion: apps/v1
kind: Deployment
metadata:
  name: manael
  labels:
    app: manael
spec:
  selector:
    matchLabels:
      app: manael
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: manael
    spec:
      containers:
      - name: manael
        image: ghcr.io/manaelproxy/manael:3.0.3@sha256:2bcc95cae0d37aa1285f3c0fc245b4b353a4f21df88da582c3e690752315dc6c
        env:
        - name: MANAEL_ENABLE_AVIF
          value: "true"
        ports:
        - containerPort: 8080
