apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:c555c5536731fb09861985aeacec6b853eb889e9c0f71bdfc9516cf0c2f2797f
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/rails", "db:migrate"]
      restartPolicy: Never
