apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:93fe26494c0ede5a57cf085a515537e07368e2c1cfef7be86ab65900b07704df
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/rails", "db:migrate"]
      restartPolicy: Never
