apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:2dff4c775bb7c5d7c5b0e7aceeb1326645461435fd4f08ad323a4e278bca4c7a
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/rails", "db:migrate"]
      restartPolicy: Never
