apiVersion: batch/v1
kind: Job
metadata:
  name: search-deploy
spec:
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:9036f3629c89349f6dc7fd3fef422c909b385e09c2c61c91608db5ea93eec6f6
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/tootctl", "search", "deploy"]
      restartPolicy: Never
