apiVersion: batch/v1
kind: Job
metadata:
  name: search-deploy
spec:
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:6cef955cbadeb25ffa6ba8f9e2ded5583a7d711f2a43d75bbbd9b447c42e8a86
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/tootctl", "search", "deploy"]
      restartPolicy: Never
