apiVersion: batch/v1
kind: Job
metadata:
  name: search-deploy
spec:
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:00fd126dc3b2c0d0e90751dbdea4cf1445b6151e7827ebc4c3b00caefb25a4e6
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/tootctl", "search", "deploy"]
      restartPolicy: Never
