apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
  labels:
    app: mastodon-web
spec:
  selector:
    matchLabels:
      app: mastodon-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mastodon-web
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:9036f3629c89349f6dc7fd3fef422c909b385e09c2c61c91608db5ea93eec6f6
        command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            port: 3000
            path: /health
          initialDelaySeconds: 180
          timeoutSeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 3000
            path: /health
          initialDelaySeconds: 180
          timeoutSeconds: 15
          periodSeconds: 30
